[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel"]

[phases.install]
cmds = ["python3 -m pip install --break-system-packages -r backend/requirements.txt"]

[phases.build]
cmds = []

[phases.start]
cmd = "python3 backend/app.py"
